%% 
%% โหลดไลบรารีและเคลียร์ค่า
clc;
clear;
close all;

%% สร้าง Link แต่ละแกน
% DH Parameters ของ Motoman MH5

L(1) = Link('revolute', ...
    'd', 0.310, ...
    'a', 0.088, ...
    'alpha', -pi/2, ...
    'standard');

L(2) = Link('revolute', ...
    'd', 0, ...
    'a', 0.310, ...
    'alpha', 0, ...
    'offset', -pi/2, ...
    'standard');

L(3) = Link('revolute', ...
    'd', 0, ...
    'a', 0.040, ...
    'alpha', -pi/2, ...
    'standard');

L(4) = Link('revolute', ...
    'd', 0.305, ...
    'a', 0, ...
    'alpha', pi/2, ...
    'standard');

L(5) = Link('revolute', ...
    'd', 0, ...
    'a', 0, ...
    'alpha', -pi/2, ...
    'standard');

L(6) = Link('revolute', ...
    'd', 0.080, ...
    'a', 0, ...
    'alpha', 0, ...
    'standard');

%% Joint Limits
L(1).qlim = deg2rad([-170 170]);
L(2).qlim = deg2rad([-65 150]);
L(3).qlim = deg2rad([-136 255]);
L(4).qlim = deg2rad([-190 190]);
L(5).qlim = deg2rad([-125 125]);
L(6).qlim = deg2rad([-360 360]);

%% สร้าง SerialLink
robot = SerialLink(L, 'name', 'Motoman MH5');

%% แสดงตาราง DH ใน Command Window
robot

%% กำหนดตำแหน่งเริ่มต้น
q0 = [0 0 0 0 0 0];

%% Forward Kinematics
T = robot.fkine(q0);

disp('Forward Kinematics =');
disp(T);

%% แสดงโมเดล 3D
figure('Name','Yaskawa Motoman MH5');

robot.plot(q0, ...
    'workspace', [-0.8 0.8 -0.8 0.8 -0.2 1.0], ...
    'tilesize', 0.1);

%% Teach Pendant
robot.teach(q0);